# Generated by Django 2.1.3 on 2018-12-18 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=233)),
                ('kod_mo', models.CharField(max_length=30)),
                ('adress_mo', models.CharField(max_length=255)),
                ('email_mo', models.EmailField(max_length=254)),
                ('coordinates_google', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PhotoMO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='img/photo/%Y/%m/')),
                ('mo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_site.MO')),
            ],
        ),
    ]
