# Generated by Django 2.1.3 on 2018-12-19 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mo',
            options={'ordering': ['name'], 'verbose_name_plural': 'MO'},
        ),
    ]
